---
name: Kube-linter-CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ixxel/unit-tests-alpine:latest
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Kube-linter IaC security scan
      uses: ixxeL-actions/kube-linter@main
      with:
        format: plain
        all-builtin: 'true'
        exit-zero: 'true'
        working-dir: .
